# Site settings
title: Taha Khan
name: Taha Khan
email: tkhan@wlu.edu

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tahakhan.net" # the base hostname & protocol for your site
github_username:  tkrad
linkedin: true
google_scholar: true

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job_title: "Assistant Professor"
excerpt_separator: "<!--more-->"

defualt:
  - scope:
    path: "files/"
    
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""